// config.js
const CONFIG = {
    GOOGLE_API_KEY: "AIzaSyAv0eINGFdlMmMdCB-JsgyJ7C1uDHYMNhQ",
    GOOGLE_SEARCH_ENGINE_ID: "c1415a5bba2664a8c",
    GEMINI_API_KEY: 'AIzaSyCG3kwDGyqojZJHAUXLfigP-YMute2Qvdo'
}
